Return-Path: <reiserfs-devel-owner@vger.kernel.org>
X-Original-To: lists+reiserfs-devel@lfdr.de
Delivered-To: lists+reiserfs-devel@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id 38DB26CA1FC
	for <lists+reiserfs-devel@lfdr.de>; Mon, 27 Mar 2023 13:03:48 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S229606AbjC0LDq (ORCPT <rfc822;lists+reiserfs-devel@lfdr.de>);
        Mon, 27 Mar 2023 07:03:46 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:46752 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S232186AbjC0LDp (ORCPT
        <rfc822;reiserfs-devel@vger.kernel.org>);
        Mon, 27 Mar 2023 07:03:45 -0400
Received: from mail-il1-f200.google.com (mail-il1-f200.google.com [209.85.166.200])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id 4D35C420F
        for <reiserfs-devel@vger.kernel.org>; Mon, 27 Mar 2023 04:03:44 -0700 (PDT)
Received: by mail-il1-f200.google.com with SMTP id d3-20020a056e02050300b00317999dcfb1so5640404ils.4
        for <reiserfs-devel@vger.kernel.org>; Mon, 27 Mar 2023 04:03:44 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20210112; t=1679915023;
        h=to:from:subject:message-id:date:mime-version:x-gm-message-state
         :from:to:cc:subject:date:message-id:reply-to;
        bh=DYYeZ6q74P1EC6zduiIqaHw2RbP3mCxfZ8UiARotK1k=;
        b=whpw/vbv5L74ZKhLBX8eBA/0I29rAqQOxyDxJkZQlw+T9sV6hbmuTB9EyHD6ij0c0X
         CcLKeEcdsaAoHYm6LOTL86bWEza2vGOvC/gKJ7YYX5u9JmccvFqc3RmrUVOsnPAv1BNg
         I+FgBP/6nxPoCZpgPy37vHkb70VreGzXOYSdoMm1/ulKx4IMSPoZC/s4mGskgaFNY07C
         O9x/X3QdRlHtPo1xUW0K1lo73QLWGDJSbqxxVwj11GV4hCsc97KuMCjxNcgJt3N8sWit
         mfvuruFKYCGxZY0HA07Zjz4t/iX2whBbL3ifqh/sJClWYBWxCIHY/aVmh3RjdAp4DWhe
         I4Pw==
X-Gm-Message-State: AO0yUKUbVtgpP6QXbH1d27L26HA24lYjTf+tRNc0LaJbi+uXU5IYfysV
        Ko2Vr5l9FrKgsO44e0LV9HnNAz3VyEDTsv/fq25UmgQfndUe
X-Google-Smtp-Source: AK7set/XcoJchD1aCq3fOiCDw2F7VdfwOOgdFWvdSPCPFB48nIER7QboA+QblG5wC7F891sXF3UvUAlaLvlNbhHIjt2x7thVO1jq
MIME-Version: 1.0
X-Received: by 2002:a02:8547:0:b0:3c2:b9ba:72f9 with SMTP id
 g65-20020a028547000000b003c2b9ba72f9mr4533372jai.5.1679915023586; Mon, 27 Mar
 2023 04:03:43 -0700 (PDT)
Date:   Mon, 27 Mar 2023 04:03:43 -0700
X-Google-Appengine-App-Id: s~syzkaller
X-Google-Appengine-App-Id-Alias: syzkaller
Message-ID: <0000000000003bdd5d05f7dfb243@google.com>
Subject: [syzbot] Monthly reiserfs report
From:   syzbot <syzbot+list4a0f973260c9d6cd4fb2@syzkaller.appspotmail.com>
To:     linux-fsdevel@vger.kernel.org, linux-kernel@vger.kernel.org,
        reiserfs-devel@vger.kernel.org, syzkaller-bugs@googlegroups.com
Content-Type: text/plain; charset="UTF-8"
X-Spam-Status: No, score=0.6 required=5.0 tests=FROM_LOCAL_HEX,
        HEADER_FROM_DIFFERENT_DOMAINS,RCVD_IN_DNSWL_NONE,RCVD_IN_MSPIKE_H2,
        SPF_HELO_NONE,SPF_PASS autolearn=no autolearn_force=no version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <reiserfs-devel.vger.kernel.org>
X-Mailing-List: reiserfs-devel@vger.kernel.org

Hello reiserfs maintainers/developers,

This is a 30-day syzbot report for the reiserfs subsystem.
All related reports/information can be found at:
https://syzkaller.appspot.com/upstream/s/reiserfs

During the period, 4 new issues were detected and 0 were fixed.
In total, 78 issues are still open and 16 have been fixed so far.

Some of the still happening issues:

Crashes Repro Title
1220    No    KASAN: slab-out-of-bounds Read in search_by_key (2)
              https://syzkaller.appspot.com/bug?extid=b3b14fb9f8a14c5d0267
1096    Yes   WARNING in reiserfs_lookup
              https://syzkaller.appspot.com/bug?extid=392ac209604cc18792e5
1069    Yes   kernel BUG at fs/reiserfs/journal.c:LINE!
              https://syzkaller.appspot.com/bug?extid=6820505ae5978f4f8f2f
853     Yes   INFO: task hung in iterate_supers
              https://syzkaller.appspot.com/bug?extid=2349f5067b1772c1d8a5
565     No    KMSAN: uninit-value in reiserfs_new_inode (2)
              https://syzkaller.appspot.com/bug?extid=6450929faa7a97cd42d1
331     Yes   possible deadlock in mnt_want_write_file
              https://syzkaller.appspot.com/bug?extid=1047e42179f502f2b0a2
168     Yes   possible deadlock in reiserfs_ioctl
              https://syzkaller.appspot.com/bug?extid=79c303ad05f4041e0dad
122     Yes   WARNING in reiserfs_readdir_inode
              https://syzkaller.appspot.com/bug?extid=798ffe5fe3e88235db59
54      Yes   possible deadlock in path_openat (2)
              https://syzkaller.appspot.com/bug?extid=a844a888fbc0ba4829ce
45      Yes   BUG: unable to handle kernel paging request in path_openat
              https://syzkaller.appspot.com/bug?extid=59a66cac604a6b49ecce

---
This report is generated by a bot. It may contain errors.
See https://goo.gl/tpsmEJ for more information about syzbot.
syzbot engineers can be reached at syzkaller@googlegroups.com.
